/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(codec2_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fd31fe33fb6953019ab4db8ea52e4789) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m17/codec2_encoder.h>
// pydoc.h is automatically generated in the build directory
//#include <codec2_encoder_pydoc.h>

void bind_codec2_encoder(py::module &m) {

  using codec2_encoder = ::gr::m17::codec2_encoder;

  py::class_<codec2_encoder, gr::block, gr::basic_block, std::shared_ptr<codec2_encoder>>(
      m, "codec2_encoder", "Codec2 encoder block")

      .def(py::init(&codec2_encoder::make), "Create a Codec2 encoder")

      ;
}
