/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(codec2_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1b2f013e25a1c90973f41cab79e6251f) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m17/codec2_decoder.h>
// pydoc.h is automatically generated in the build directory
//#include <codec2_decoder_pydoc.h>

void bind_codec2_decoder(py::module &m) {

  using codec2_decoder = ::gr::m17::codec2_decoder;

  py::class_<codec2_decoder, gr::block, gr::basic_block, std::shared_ptr<codec2_decoder>>(
      m, "codec2_decoder", "Codec2 decoder block")

      .def(py::init(&codec2_decoder::make), "Create a Codec2 decoder")

      ;
}
