/*
 * m17_coder_pydoc.h
 * 
 * GNU Radio M17 Module - Python Documentation Headers
 * 
 * This file contains Python documentation strings for the M17 coder block.
 * It's automatically generated by the docstring extraction system.
 */

#ifndef INCLUDED_M17_CODER_PYDOC_H
#define INCLUDED_M17_CODER_PYDOC_H

// Define the D() macro for docstring access
// The D() macro can take one or two arguments
#define D(...) D_HELPER(__VA_ARGS__, D_TWO, D_ONE)(__VA_ARGS__)
#define D_HELPER(a, b, c, ...) c
#define D_ONE(class_name) __doc_##class_name
#define D_TWO(class_name, method_name) __doc_##class_name##_##method_name

// Python docstrings for M17 coder block
static const char* __doc_m17_coder = R"doc(
M17 Coder Block

This block encodes M17 digital radio frames.

Args:
    debug (bool): Enable debug output
    signed_str (bool): Enable signed string processing  
    seed (str): Seed for random number generation

Returns:
    M17 encoded frames
)doc";

// Additional docstrings for methods - these match the D() macro usage
static const char* __doc_m17_coder_make = R"doc(Create M17 coder block)doc";
static const char* __doc_m17_coder_set_key = R"doc(Set encryption key)doc";
static const char* __doc_m17_coder_set_priv_key = R"doc(Set private key)doc";
static const char* __doc_m17_coder_set_seed = R"doc(Set seed)doc";
static const char* __doc_m17_coder_set_meta = R"doc(Set metadata)doc";
static const char* __doc_m17_coder_set_src_id = R"doc(Set source ID)doc";
static const char* __doc_m17_coder_set_dst_id = R"doc(Set destination ID)doc";
static const char* __doc_m17_coder_set_debug = R"doc(Set debug mode)doc";
static const char* __doc_m17_coder_set_signed = R"doc(Set signed mode)doc";
static const char* __doc_m17_coder_set_type = R"doc(Set frame type)doc";
static const char* __doc_m17_coder_set_mode = R"doc(Set mode)doc";
static const char* __doc_m17_coder_set_data = R"doc(Set data)doc";
static const char* __doc_m17_coder_set_encr_type = R"doc(Set encryption type)doc";
static const char* __doc_m17_coder_set_encr_subtype = R"doc(Set encryption subtype)doc";
static const char* __doc_m17_coder_set_aes_subtype = R"doc(Set AES subtype)doc";
static const char* __doc_m17_coder_set_can = R"doc(Set CAN)doc";

#endif // INCLUDED_M17_CODER_PYDOC_H
