/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(symbol_sync.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4ec639e9240885585e0150143e448f25) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/m17/symbol_sync.h>
// pydoc.h is automatically generated in the build directory
//#include <symbol_sync_pydoc.h>

void bind_symbol_sync(py::module &m) {

  using symbol_sync = ::gr::m17::symbol_sync;

  py::class_<symbol_sync, gr::block, gr::basic_block, std::shared_ptr<symbol_sync>>(
      m, "symbol_sync", "Symbol sync block")

      .def(py::init(&symbol_sync::make), py::arg("in_sps"), py::arg("loop_bw"),
           py::arg("max_dev"), "Create a symbol sync block")

      .def("set_in_sps", &symbol_sync::set_in_sps, py::arg("in_sps"),
           "Input samples per symbol")

      .def("set_loop_bw", &symbol_sync::set_loop_bw, py::arg("loop_bw"),
           "Loop bandwidth")

      .def("set_max_dev", &symbol_sync::set_max_dev, py::arg("max_dev"),
           "Maximum deviation")

      ;
}
